### ISSUE TITLE
Annotating subexpressions

### ISSUE THREAD

**Issue by knightzmc** [Gabriella439/grace#60]
Hey, firstly just wanted to thank you for this resource - it's been very useful!

I'd like to desugar my language into something like GHC's Core, which means I need to be able to annotate subexpressions with types. This algorithm doesn't seem to support that out of the box, and the adjustments I've poorly made haven't worked very well.
Do you know if this is possible / practical to do? Any pointers as to how I could do this?

Thanks a lot!

**Comment by Gabriella439** [comment]
Grace supports type annotations (i.e. `expression : type`), although I wasn't sure if you meant something different

**Comment by Gabriella439** [comment]
Oh, this is not something that I know as much about, but my rough intuition is that it should be possible because while type-checking every expression is checked against a type (in which case you can use the type it is checked against as the annotation) or a type is inferred (in which case you can use the inferred type as the annotation).

Conceptually, the types of the `infer` and `check` function would change so that each of them would now also return the annotated expression in their result (although, I haven't tried to actually implement this, so I don't know if I'm missing some other crucial detail).

**Comment by knightzmc** [comment]
Thanks for the pointers. I tried something similar but had a few issues with types being solved too generally, or not solved at all.
For example, in an expression like `let id = \x -> x`, the second `x` would either be kept as an unsolved type, or be incorrectly `complete`'d to `∀a. a`, but that's probably me taking the wrong approach. I'll do some more experimenting and hopefully I can get something working.


Out of curiosity, is this an unusual requirement? The fact that most algorithms don't seem to support this makes me think so, but keeping type information doesn't seem like an unreasonable idea, often essential depending on the compilation target. I keep wondering if perhaps this is one giant XY problem...

**Comment by Gabriella439** [comment]
Oh yeah, the potential presence of unsolved types as you go makes this a bit trickier to do.  It's probably still possible, but would probably require a significant refactor of the code (e.g. maybe it would involve collecting the final context and doing one last pass over the annotations to solve all type variables although maybe there's a more elegant solution).

I think "elaboration" (annotating an AST with types) is a pretty common thing to do for compilers, so I don't think your request is unreasonable.

**Comment by Gabriella439** [comment]
You're welcome!

**Comment by knightzmc** [comment]
I've made some decent progress but am running into the same over-generalisation issue as before. 
I have an idea solution, but could use a sanity-check:

My current strategy is to collect a write-only log of the whole context, so as to include things like lambda parameter annotations, then use that to `complete` every sub-expression in a top-down way. All my variables are given unique names so I don't think this should present any issues.

The example I'm trying to check is `let id = \x_0 -> x_0`

**Comment by knightzmc** [comment]
For what it's worth this approach has worked for most simple cases! I've not tested it with anything complex yet, but as a general process it seems sound

If you're interested, the implementation is pretty concise: https://github.com/ElaraLang/elara/blob/f0f677f9f20e323d2b17a01997bebc62dbf3af2d/src/Elara/TypeInfer.hs#L242

Going to close this now, thanks again for your pointers and for indirectly rubber ducky-ing :)

**Comment by Gabriella439** [comment]
You're welcome!
