### ISSUE TITLE
Union `subtype` Union: p0 == p1 not handled?

### ISSUE THREAD

**Issue by gardspirito** [Gabriella439/grace#63]
https://github.com/Gabriella439/grace/blob/cd70563b5bc2793aa1ad905309c2c9f00550603c/src/Grace/Infer.hs#L667-L669
— here, it's assumed that either `p0` is first and `p1` follows it or `p1` is first and `p0` follows it.
The case where `p0` **is** `p1` is not handled.

Does it always have to be true?
(Asking because I ran into `Internal error`)

**Comment by Gabriella439** [comment]
Oh, you're right, the case where `p0 == p1` isn't correctly handled there and should be treated as a successful unification

**Comment by gardspirito** [comment]
Sorry for the confusion: my use-case actually involved Union, not Record. And Union doesn't have a check that Record has:
```diff
diff --git a/src/Grace/Infer.hs b/src/Grace/Infer.hs
index 5db239d..3cca626 100644
--- a/src/Grace/Infer.hs
+++ b/src/Grace/Infer.hs
@@ -629,6 +629,9 @@ subtype _A0 _B0 = do
             traverse_ process both
 
             case (alternatives0, alternatives1) of
+                _ | null extraA && null extraB && alternatives0 == alternatives1 -> do
+                        return ()
+
                 (Monotype.UnsolvedAlternatives p0, Monotype.UnsolvedAlternatives p1) -> do
                     p2 <- fresh
```
?

And still, isn't it possible for `p0 == p1` & `null extraA && null extraB == False`?
